/* Generate one static HTML page per project (projects/<id>.html) plus
   sitemap.xml, from the project data in js/data.js.
   Usage: node tools/build-pages.js   (npm run build runs it after the JSX
   compile). Each page sets window.PROJECT_ID and loads only the data files
   that project actually uses; js/app.js then renders that single story. */
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = path.join(__dirname, "..");
const SITE = "https://adhi-climate.vercel.app";

// Evaluate js/data.js in a sandbox to get window.PORTFOLIO.
const sandbox = { window: {} };
vm.runInNewContext(fs.readFileSync(path.join(ROOT, "js", "data.js"), "utf8"), sandbox);
const P = sandbox.window.PORTFOLIO;
if (!P || !Array.isArray(P.projects)) throw new Error("js/data.js did not define window.PORTFOLIO.projects");

const esc = (s) => String(s)
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

function scriptsFor(p) {
  const srcs = ["/js/data.js", "/js/chartdata.js"];
  if (p.hasMap || p.rainMap) srcs.push("/js/mapdata.js");
  if (p.scrolly || p.rainScrolly) srcs.push("/js/scrollydata.js");
  if (p.matrix) srcs.push("/js/aasbdata.js");
  srcs.push("/js/icons.js", "/js/components.js", "/js/charts.js", "/js/sections.js", "/js/app.js");
  return srcs.map((s) => `<script src="${s}"></script>`).join("\n");
}

function pageHtml(p, i) {
  const title = `${p.title} · ${P.profile.name}`;
  const url = `${SITE}/projects/${p.id}.html`;
  return `<!DOCTYPE html>
<!-- GENERATED by tools/build-pages.js from js/data.js. Do not edit by hand:
     change the project data or the generator, then run npm run build. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<meta name="description" content="${esc(p.summary)}">
<meta name="author" content="${esc(P.profile.name)}">
<meta name="theme-color" content="#14224A">

<meta property="og:type" content="article">
<meta property="og:site_name" content="${esc(P.profile.name)}">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(p.summary)}">
<meta property="og:url" content="${url}">
<meta property="og:image" content="${SITE}/assets/og-card.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${esc(title)}">
<meta name="twitter:description" content="${esc(p.summary)}">
<meta name="twitter:image" content="${SITE}/assets/og-card.png">
<link rel="canonical" href="${url}">

<link rel="stylesheet" href="/styles.css">
<link rel="stylesheet" href="/portfolio.css">
<link rel="icon" href="/assets/logo-mark.svg">
<script>
  (function () {
    try {
      var t = localStorage.getItem("theme");
      if (!t) t = (window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches) ? "dark" : "light";
      document.documentElement.setAttribute("data-theme", t);
    } catch (e) {}
  })();
</script>
<script crossorigin src="https://unpkg.com/react@18.3.1/umd/react.production.min.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@18.3.1/umd/react-dom.production.min.js"></script>
</head>
<body>
<div id="root"></div>

<script>window.PROJECT_ID = ${JSON.stringify(p.id)};</script>
${scriptsFor(p)}
</body>
</html>
`;
}

const outDir = path.join(ROOT, "projects");
fs.mkdirSync(outDir, { recursive: true });

// Remove pages for projects that no longer exist, then write the current set.
for (const f of fs.readdirSync(outDir)) {
  if (f.endsWith(".html") && !P.projects.some((p) => p.id + ".html" === f)) {
    fs.unlinkSync(path.join(outDir, f));
    console.log("removed stale projects/" + f);
  }
}
P.projects.forEach((p, i) => {
  fs.writeFileSync(path.join(outDir, p.id + ".html"), pageHtml(p, i));
});
console.log(`generated ${P.projects.length} project pages in projects/`);

const today = new Date().toISOString().slice(0, 10);
const urls = [`${SITE}/`].concat(P.projects.map((p) => `${SITE}/projects/${p.id}.html`));
fs.writeFileSync(path.join(ROOT, "sitemap.xml"),
  `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  urls.map((u) => `  <url><loc>${u}</loc><lastmod>${today}</lastmod></url>`).join("\n") +
  `\n</urlset>\n`);
console.log("generated sitemap.xml");
